
Write-host "deploy.ps1"
Write-host "APPVEYOR_PROJECT_SLUG: $env:APPVEYOR_PROJECT_SLUG"
Write-host "APPVEYOR_REPO_COMMIT_AUTHOR: $env:APPVEYOR_REPO_COMMIT_AUTHOR"
Write-host "APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL: $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL"
#throw "failed1"
